<?php
/***********************************************************************************/
/* WARNING:                                                                        */
/* The wp-config.php file is automatically generated by Flywheel. You will not be  */
/* able to edit this file yourself. Defines needed for plugins can be added to a   */
/* php file in your wp-content/mu-plugins directory. If you need to add defines    */
/* for core WordPress functionality, please contact Flywheel support at            */
/* help@getflywheel.com.                                                           */
/***********************************************************************************/

define('FLYWHEEL_CONFIG_DIR', dirname(__FILE__) . '/flywheel-config');
define('FLYWHEEL_PLUGIN_DIR', FLYWHEEL_CONFIG_DIR . '/plugins');
define('FLYWHEEL_DEFAULT_PROTOCOL', 'https://');
define('WP_PLUGIN_DIR', dirname(__FILE__) . '/wp-content/plugins');
define('WPMU_PLUGIN_DIR', dirname(__FILE__) . '/wp-content/mu-plugins');
define('WPMU_PLUGIN_URL', '/wp-content/mu-plugins');
define('FS_METHOD', 'direct');
define('WP_POST_REVISIONS',  10);
define('WP_MEMORY_LIMIT', '200M');


/****************************************************************************/
/*                           Domain Configuration                           */
/****************************************************************************/
if ( !(defined('WP_CLI') && WP_CLI) ) {
    define('WP_SITEURL', FLYWHEEL_DEFAULT_PROTOCOL . 'csleon.com');
    define('WP_HOME', FLYWHEEL_DEFAULT_PROTOCOL . 'csleon.com');
}




/****************************************************************************/
/*                         Database Configuration                           */
/****************************************************************************/
define('DB_NAME', 'db4938527695');
define('DB_USER', 'fw3581557720');
define('DB_PASSWORD', 'j5OX8nz58zy5MX6Nuf3kGkXYP8FFPC');
define('DB_HOST', '127.0.0.1');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');
$table_prefix  = 'wp_5lbhgador7_';


/****************************************************************************/
/*                          Plugin Configuration                            */
/****************************************************************************/




/****************************************************************************/
/*                             WordPress Salts                              */
/****************************************************************************/
define('AUTH_KEY',          '?AF$<L8o]0/8(8ESd-Bc}tqatbjj;N&61VfcMrc5Xyo;Y(~ss#:AR&gH{/+N$6]Z');
define('SECURE_AUTH_KEY',   '@w]8U$Zd2hH-=_8!OgPQ6{tN-ZeFx`$BR-8qqz.0]-F<F1;[my2Nz/Wyb417r0Un');
define('LOGGED_IN_KEY',     ']C7~UJaf#yjS>St6pZf_PoBx%>lsYwJZ`QHa~(p/y^~8@^JKW?+*#z8U9O!YX@4|');
define('NONCE_KEY',         'Yz+j]w41krJ48s5v!W0GY>|-w`!&+dOq$h,wqe*AS~N>MGg<-n_:42~4#0@%FwtY');
define('AUTH_SALT',         '*5QYZNZeI*_VSb2Cs2o2*S[a^KJAEaNDXLufliNN.X[|OO+X|/v<#EZn2e(XE,oH');
define('SECURE_AUTH_SALT',  '2Pc9}w|Pjx8yGB#l#oZ{,?71@zz%F]h4w,L(XMY]zd7:gWOJw]oYViq2.BZl~;Cy');
define('LOGGED_IN_SALT',    'LtCT!dg6m(!nk<tI1F&M~Vd!1UoZohDwr`~L;)h<}>i!ouY@((SyNH->C]gH]6hp');
define('NONCE_SALT',        'Z0L4:zwTrj;^$B}luasxOY.8Aec5#$<Ei29K0Rn^L1.`A-%1JTO=-6/b%<$?EV~[');


/****************************************************************************/
/*                        General WordPress Settings                        */
/****************************************************************************/
define('WPLANG', '');
define('WP_DEBUG', false);
define('WP_CACHE', false);
define('WP_DEBUG_LOG', false);




/****************************************************************************/
/*                     Disable WordPress Auto-updates                       */
/*           http://getflywheel.com/flywheel-wordpress-3-7/                 */
/****************************************************************************/
define('WP_AUTO_UPDATE_CORE', false);


if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');

if ( array_key_exists('HTTP_X_FORWARDED_PROTO', $_SERVER) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' )
	$_SERVER['HTTPS']='on';



require_once(ABSPATH . 'wp-settings.php');
